name: Deploy Static Site

on:
  push:
    branches:
      - main
    paths-ignore:
      - backend/**
      - README.md
      - Dockerfile
      - .dockerignore
      - .gitignore
  # schedule:
  #  - cron: '0 18 * * *'  # Run at 12:00 PM Denver time (18:00 UTC)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: ./bin/bun install --frozen-lockfile

      - name: Build Static Site
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          ./bin/bun run build -- --base /${REPO_NAME}/
        env:
          STATIC_BUILD: true
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          single-commit: true
          # dry-run: true
